# Default values for traefik-forward-auth.
replicaCount: 1

image:
  repository: thomseddon/traefik-forward-auth
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

traefikForwardAuth:
  logging:
    # [trace|debug|info|warn|error|fatal|panic] Log level (default: warn)
    level: ""
    # [text|json|pretty] Log format (default: text)
    format: ""
  # Single host to use when returning from 3rd party auth
  authHost: ""
  restrictions:
    # Only allow given email domains. (Comma delimited)
    domain: ""
    # Only allow given email addresses. (Comma delimited)
    whitelist: ""
  # Lifetime in seconds (default: 43200)
  lifetime: ""
  cookie:
    # Domain(s) to set auth cookie on. (Comma delimited)
    domain: ""
    # Use insecure cookies
    insecure: ""
    # Cookie Name (default: _forward_auth)
    name: ""
    # CSRF Cookie Name (default: _forward_auth_csrf)
    csrfName: ""
  default:
    # [auth|allow] Default action (default: auth)
    action: ""
    # [google|oidc|generic-oauth] Default provider (default: google)
    provider: ""
  # URL to redirect to following logout
  logoutRedirect: ""
  # Callback URL Path (default: /_oauth)
  urlPath: ""
  # Secret used for signing. If empty, one will be generated. If specifying your own in env use "-"
  secret: ""
  # Not yet implemented
  rules:
    {}
    # example_public:
    #   action: allow
    #   rule: Host("stats.example.com") && PathPrefix("/api/public")
  middleware:
    enabled: false
    name: ""
  providers:
    google:
      enabled: false
      clientId: ""
      clientSecret: ""
      prompt: ""
    oidc:
      enabled: false
      issuerUrl: ""
      clientId: ""
      clientSecret: ""
      resource: ""
    genericOauth:
      enabled: false
      authUrl: ""
      tokenUrl: ""
      userUrl: ""
      clientId: ""
      clientSecret: ""
      scope: ""
      tokenStyle: ""
      resource: ""

env: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 4181
  ## Provide any additional annotations which may be required. This can be used to
  ## set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}
  labels: {}
  additionalSpec: {}

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
