{{- if .Values.traefikForwardAuth.middleware.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.traefikForwardAuth.middleware.name | default "traefik-forward-auth" }}
spec:
  forwardAuth:
    address: "http://{{ include "traefik-forward-auth.fullname" . }}:{{ .Values.service.port }}"
    authResponseHeaders:
      - X-Forwarded-User
  {{- end }}